# Generated by Django 2.2.5 on 2020-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200301_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/static/noimage.png', upload_to=''),
        ),
    ]
