# Generated by Django 2.2.5 on 2020-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200301_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='noimage.png', upload_to=''),
        ),
    ]
